"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../../lib/supabase/client";

type MenuItem={id:string;name:string;category_id:string|null;menu_categories?:{name:string}|null};
type Option={id:string;menu_item_id:string;name:string;price:number;is_available:boolean};
const money=(n:number)=>`$${Number(n||0).toFixed(2)}`;
const parse=(name:string)=>{const m=name.match(/^(.+?)\s*-\s*(.+)$/);return m?{level:m[1].trim(),size:m[2].trim()}:{level:"Options",size:name.trim()}};
export default function OwnerPrices(){const s=createClient();const [items,setItems]=useState<MenuItem[]>([]);const [options,setOptions]=useState<Option[]>([]);const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState<Record<string,Option>>({});const [error,setError]=useState("");const [message,setMessage]=useState("");
const load=async()=>{setError("");const [m,o]=await Promise.all([s.from("menu_items").select("id,name,category_id,menu_categories(name)").order("name"),s.from("menu_item_options").select("id,menu_item_id,name,price,is_available").order("name")]);if(m.error||o.error){setError((m.error||o.error)?.message||"Could not load prices.");return;}setItems((m.data||[]) as any);setOptions((o.data||[]).map((x:any)=>({...x,price:Number(x.price)||0})));};useEffect(()=>{load()},[]);
const grouped=useMemo(()=>items.map(item=>({item,options:options.filter(o=>o.menu_item_id===item.id)})).filter(x=>x.options.length),[items,options]);
const start=(o:Option)=>{setDraft(d=>({...d,[o.id]:{...o}}));setEditing(o.id)};const save=async(id:string)=>{const x=draft[id];if(!x)return;const {error}=await s.from("menu_item_options").update({name:x.name,price:Number(x.price)||0,is_available:x.is_available}).eq("id",id);if(error){setError(error.message);return;}setOptions(os=>os.map(o=>o.id===id?x:o));setEditing(null);setMessage(`${x.name} saved.`)};
return <main style={{maxWidth:980,margin:"0 auto",padding:"24px"}}><header style={{marginBottom:24}}><p style={{letterSpacing:2,fontWeight:800,margin:0}}>PRICING CENTER</p><h1 style={{margin:"6px 0"}}>Levels, sizes & prices</h1><p>These are the exact options customers see. Tea options are grouped by level, then by the sizes available for that level.</p><button onClick={load}>↻ Refresh</button></header>{message&&<p>{message}</p>}{error&&<p>{error}</p>}{grouped.map(({item,options:rows})=>{const byLevel=new Map<string,Option[]>();rows.forEach(o=>{const p=parse(o.name);byLevel.set(p.level,[...(byLevel.get(p.level)||[]),o])});return <section key={item.id} style={{border:"1px solid #ddd",borderRadius:16,padding:18,marginBottom:16}}><h2 style={{marginTop:0}}>{item.menu_categories?.name||"Menu"} · {item.name}</h2>{[...byLevel.entries()].map(([level,list])=><div key={level} style={{marginTop:16}}><h3 style={{marginBottom:8}}>{level}</h3>{list.map(o=>{const p=parse((editing===o.id?draft[o.id]:o).name);const x=editing===o.id?draft[o.id]:o;return <div key={o.id} style={{display:"grid",gridTemplateColumns:"minmax(110px,1fr) 120px 120px 100px",gap:8,alignItems:"center",padding:"8px 0",borderTop:"1px solid #eee"}}>{editing===o.id?<input value={x.name} onChange={e=>setDraft(d=>({...d,[o.id]:{...x,name:e.target.value}}))}/>:<strong>{p.size}</strong>}{editing===o.id?<input type="number" step="0.01" value={x.price} onChange={e=>setDraft(d=>({...d,[o.id]:{...x,price:Number(e.target.value)}}))}/>:<span>{money(o.price)}</span>}<label><input type="checkbox" disabled={editing!==o.id} checked={x.is_available} onChange={e=>setDraft(d=>({...d,[o.id]:{...x,is_available:e.target.checked}}))}/> Available</label>{editing===o.id?<><button onClick={()=>save(o.id)}>Save</button><button onClick={()=>setEditing(null)}>Cancel</button></>:<button onClick={()=>start(o)}>✏ Edit</button>}</div>})}</div>)}</section>})}</main>}
